version: "3.0"
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: apuestasdb
    ports:
      - "3306:3306"

  apuestasdb:
    build: .
    ports:
      - "8090:8090"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: 123456
